version: '2'

services:
  api:
    build:
      context: ./
    container_name: peckergo_api
    volumes:
      - ./peckergo:/app/peckergo
      - ./api/config/config.yml.prod:/app/config/config.yml:ro
      - ./zoneinfo.zip:/usr/local/go/lib/time/zoneinfo.zip:ro
      - /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro
    network_mode: host
    # ports:
    #   - "8901:8000"
    restart: always


