corsEnable: true

serverPort: 8000

log:
  # 0 = Panic 1 = Fatal 2 = Error 3 = Warn 4 = Info 5 = Debug
  logLevel: 5

router:
  # debug release test
  logMode: "debug"

db:
  dsn: "root:root@tcp(localhost:3306)/peckergo?charset=utf8&parseTime=true"
  showLog: true

redis:
  addr: "localhost:6379"

# 默认管理员用户名密码
admin:
  userName: "admin"
  password: "admin"