corsEnable: true

trackingServerURL: "http://localhost:8000" 

serverPort: 8000

log:
  # 0 = Panic 1 = Fatal 2 = Error 3 = Warn 4 = Info 5 = Debug
  logLevel: 5

router:
  # debug release test
  logMode: "debug"

db:
  dbName: "peckergo"
  dsn: "root:root@tcp(localhost:3306)/peckergo?parseTime=true"
  showLog: true

redis:
  Addr: "localhost:6379"

# 默认管理员用户名密码
admin:
  userName: "admin"
  password: "admin"

# stack 错误崩溃日志上报 不用可关闭
slack:
  enabled: false
  channel: "#peckergo"
  key: "TC43M8257/BC4G2E36X/lpOiyrBUF0BIyeEB6EqWaidK"
  