corsEnable: true

serverPort: 8000

log:
  # 1 = debug 2 = info 3 = warn 4 = error 5 = fatal 6 = panic
  logLevel: 1

router:
  # debug release test
  logMode: "debug"

db:
  dsn: "root:root@tcp(localhost:3306)/console-template?charset=utf8&parseTime=true"
  showLog: true

# 默认管理员用户名密码
admin:
  userName: "admin"
  password: "admin"